#!/usr/bin/env python

import sys

demanglemap = {
    "_RNvCsie3AuTHCqpB_10rust_hello4calc": "rust_hello::calc",
    "_RNvCsie3AuTHCqpB_10rust_hello4main": "rust_hello::main",
}

def main():
    while True:
        line = sys.stdin.readline().strip()
        print(demanglemap[line], flush=True)

if __name__ == "__main__":
    main()
