name: Docs
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # Builds docs using sphinx
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "pip install .[doc]"
        docs-folder: "docs/"

    - uses: actions/upload-artifact@v2
      with:
        name: ApiDocsHTML
        path: "docs/_build/html/"

    - name: set nojekyll for github
      run: |
        sudo touch docs/_build/html/.nojekyll

    - name: Deploy docs to gh-pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/_build/html/
        SINGLE_COMMIT: true
